djangotest_website/apps/accounts/urls.py
from django.urls import path
from . import views

from django.contrib.auth import views as auth_views

app_name='accounts'
urlpatterns = [
    path("accounts/profile", views.ProfileView.as_view(), name="profile"),
    # Django Auth
    path(
        "login",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    path("accounts/logout", auth_views.LogoutView.as_view(), name="logout"),
]

djangotest_website/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('djangotest_website.apps.public.urls')),
    path("accounts/", include('djangotest_website.apps.accounts.urls')),
    
]

djangotest_website/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class UserInterest(models.Model):
    name = models.CharField(max_length=64, unique=True)
    normalized_name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.name

class userPersona(models.Model):
    name = models.CharField(max_length=64, unique=True)
    normalized_name = models.CharField(max_length=64, unique=True)
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.name

# Create your models here.

class UserProfile(models.Model):
    #owener
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    
    #settings
    is_full_name_displayed = models.BooleanField(default=True)

    #details
    bio = models.CharField(max_length=500,blank=True,null=True)
    website = models.URLField(max_length=200,blank=True,null=True)
    persona = models.ForeignKey(userPersona, on_delete=models.SET_NULL,blank=True,null=True)
    interests =models.ManyToManyField(UserInterest, blank=True)

djangotest_website/apps/accounts/views.py
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = "accounts/profile.html"

djangotest_website/views.py
# from django.http import HttpResponse
# from django.template import loader
# from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

# def index(request):
#     return HttpResponse("Hello Django")

# def index(request):
#     template =  loader.get_template('index.html')
#     return HttpResponse(template.render({},request))


# def index(request):
#     print(request.user)
#     return render(request, "index.html")


# def about(request):
#     return render(request, "about.html")


# def contact(request):
#     return render(request, "contact.html")


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = "accounts/profile.html"

djangotest_website/templates/about.html
{% extends 'base.html' %}
{% block title %}About{% endblock %}
{% block content %}
<h1>About</h1>
{% endblock %}

djangotest_website/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}Djangotest_website-index.html{% endblock %}

{% block content %}
<h1>login</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">login</button>
</form>
{% endblock %}

djangotest_website/templates/accounts/profile.html
{% extends 'base.html' %}
{% block title %}Djangotest_website-index.html{% endblock %}
{% block content %}
<h1>
    {{ user.get_full_name }} (@{{user.username}})
</h1>
{% with profile=user.profile %}
    {% if profile %}
        <h2>
            {{ profile.persona|default:"" }}
        </h2>
        <div>
            {{ profile.bio|default:"" }}
        </div>
        <div>
            {% with website=profile.website|default:"" %}
                <a href="{{website}}">{{ website }}</a>
            {% endwith %}
        </div>
        <br/>
        <div>
            Interests:
            {% for interest in profile.interests.all %}
                <span>
                    {{ interest.name }}{% if not forloop.last %},{% endif %}
                </span>
                {% endfor %}
        </div>
    {% endif %}
{% endwith %}

{% endblock %}

djangotest_website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Djangotest_website{% endblock %}</title>
</head>
<body>
    {% include 'navbar.html' %}
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

djangotest_website/templates/contact.html
{% extends 'base.html' %}
{% block title %}Contact{% endblock %}
{% block content %}
<h1>Contact</h1>
{% endblock %}

djangotest_website/templates/index.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block content %}
<h1>hello world from template page</h1>
{% endblock %}

djangotest_website/templates/navbar.html
<nav>
    {% url 'public:index' as index_url %}
    <span>{% if request.path == index_url %}Home{% else %}<a href="{{ index_url }} ">Home</a>{% endif %}</span>
    {% url 'public:about' as about_url %}
    <span>{% if request.path == about_url %}About{% else %}<a href="{{ about_url }} ">About</a>{% endif %}</span>
    {% url 'public:contact' as contact_url %}
    <span>{% if request.path == contact_url %}Contact{% else %}<a href="{{ contact_url }} ">Contact</a>{% endif %}</span>

    <span style="float: right;">
        {% if user.is_authenticated %}
            {% url 'accounts:profile' as profile_url %}
        <span>Hello {% if request.path == profile_url %}{{ user.username }}{% else%}<a href="{{ profile_url }}">{{ user.username }}</a>{% endif %}</span>
        <span><a href="{% url 'accounts:logout' %}">Logout</a></span>
        {% else %}
        <span><a href="{% url 'accounts:login' %}">Login</a></span>
        {% endif %}
    </span>
</nav>